name: wasm

on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

# GITHUB_TOKEN のパーミッションを設定し、GitHub Pages へのデプロイを許可します
permissions:
  contents: read
  pages: write
  id-token: write

# 1 つの同時デプロイメントを可能にする
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build Wasm
        run: |
          sudo apt install meson ninja-build
          zig build --summary all -Dsokol -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall
          find zig-out
          mkdir -p public
          cp -rp zig-out/web public/wasm
      - name: start http
        run: |
          npm install
          npm start&
      # docusaurus
      - name: playwright
        run: |
          npx playwright install --with-deps chromium
          npm run ss
          echo "screenshot done"
          npm run build
      # deploy
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
